### ISSUE TITLE
Match ratio

### ISSUE THREAD

**Issue by Shu-HowTing** [lzx551402/geodesc#2]
Hi，thank you for your sharing!It is a nice  job!
Here is my little question:
```py
 deep_good_matches, deep_mask = matcher_wrapper.get_matches(
                                   deep_feat1, deep_feat2, cv_kpts1, cv_kpts2, ratio=0.80, cross_check=True, info='deep')
sift_good_matches, sift_mask = matcher_wrapper.get_matches(
                                       sift_feat1, sift_feat2, cv_kpts1, cv_kpts2, ratio=0.89, cross_check=True, info='sift')
```
The `ratio` between the  `deep` and `sift`  method should de be same, why different?

**Comment by lzx551402** [comment]
The ratio criteria should be adapted for different descriptors in order to give a good tradeoff between recall and accuracy of match inliers. You may also refer to Sec.5.1 in the original paper for details.
