### ISSUE TITLE
Extracting Descriptors on HPatches

### ISSUE THREAD

**Issue by qiuweibo** [lzx551402/geodesc#4]
Hi,

Your Geodesc implementation on different benchmarks is amazing. 

But I have a question on **extract_features_of_hpatches.py** in terms of extracting descriptors from HPatches.

`seq_data = load_seq(os.path.join(FLAGS.hpatches_root, hpatches_seq_list[i]))
 feat = sess.run("squeeze_1:0", feed_dict={"input:0": seq_data})`

I suppose these two lines are about extracting Geodesc descriptors, right? But as HPatches mentioned, every patch is extracted using scale invariant interest point detecotrs, such as DoG. And then every patch is normalized to 65*65 pixels.

So you extract exactly 1 descriptor on every patch? How did you do that? What if there is more than 1 descriptor generated? Or maybe no descriptor can be generated?

Thanks in advance.

Best regards,
Weibo Qiu.

**Comment by lzx551402** [comment]
Hi Weibo,

Thanks for your interest in our project. I'm not sure if I understand your question correctly, but yes I extract one descriptor per patch, and you may refer to load_seq function for implementation details. Basically it is quite simple: you load the patch image provided by HPatches, for example, an image of (650, 65) consisting of 10 patches, then resize to (320, 32) and further reshape to (10, 32, 32, 1) that fits the network input.

**Comment by qiuweibo** [comment]
> Hi Weibo,
> 
> Thanks for your interest in our project. I'm not sure if I understand your question correctly, but yes I extract one descriptor per patch, and you may refer to load_seq function for implementation details. Basically it is quite simple: you load the patch image provided by HPatches, for example, an image of (650, 65) consisting of 10 patches, then resize to (320, 32) and further reshape to (10, 32, 32, 1) that fits the network input.

Hi Zixin,

I referred to your paper as well. It seems you trained descriptor based on the SIFT detectors. But what I am doing now is to evaluate SIFT and LIFT which has both key point detectors and descriptors. In this case, I am not sure if HPatches are still applicable since it already extract patches using DoG.

**Comment by lzx551402** [comment]
> > Hi Weibo,
> > Thanks for your interest in our project. I'm not sure if I understand your question correctly, but yes I extract one descriptor per patch, and you may refer to load_seq function for implementation details. Basically it is quite simple: you load the patch image provided by HPatches, for example, an image of (650, 65) consisting of 10 patches, then resize to (320, 32) and further reshape to (10, 32, 32, 1) that fits the network input.
> 
> Hi Zixin,
> 
> I referred to your paper as well. It seems you trained descriptor based on the SIFT detectors. But what I am doing now is to evaluate SIFT and LIFT which has both key point detectors and descriptors. In this case, I am not sure if HPatches are still applicable since it already extract patches using DoG.

Yes you can absolutely use HPatches to evaluate different detector/descriptor combinations, you may refer to [SuperPoint](https://arxiv.org/abs/1712.07629)  about how to set up a fair configuration (e.g., same NMS, error threshold). In the provided [example](https://github.com/lzx551402/geodesc/blob/master/examples/image_matching.py) I used SIFT+GeoDesc in image matching applications. I also adopted similar strategy to benchmark on HPatches in my new paper [contextdesc](https://github.com/lzx551402/contextdesc).

**Comment by qiuweibo** [comment]
> > > Hi Weibo,
> > > Thanks for your interest in our project. I'm not sure if I understand your question correctly, but yes I extract one descriptor per patch, and you may refer to load_seq function for implementation details. Basically it is quite simple: you load the patch image provided by HPatches, for example, an image of (650, 65) consisting of 10 patches, then resize to (320, 32) and further reshape to (10, 32, 32, 1) that fits the network input.
> > 
> > 
> > Hi Zixin,
> > I referred to your paper as well. It seems you trained descriptor based on the SIFT detectors. But what I am doing now is to evaluate SIFT and LIFT which has both key point detectors and descriptors. In this case, I am not sure if HPatches are still applicable since it already extract patches using DoG.
> 
> Yes you can absolutely use HPatches to evaluate different detector/descriptor combinations, you may refer to [SuperPoint](https://arxiv.org/abs/1712.07629) about how to set up a fair configuration (e.g., same NMS, error threshold). In the provided [example](https://github.com/lzx551402/geodesc/blob/master/examples/image_matching.py) I used SIFT+GeoDesc in image matching applications. I also adopted similar strategy to benchmark on HPatches in my new paper [contextdesc](https://github.com/lzx551402/contextdesc).

Thanks for your help!
The paper and you projects are really helpful. However I feel like I cannot finish my master thesis in time. I will keep in touch with your two interesting projects.

Have a nice weekend.

Regards,
Weibo.

**Comment by lzx551402** [comment]
Sure, feel free to let me know if you have any other concerns.
